version: "3.5"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.35.4
    command: [
      "run",
      "--config", "/config/config.json",
      "--database-path", "/data/db",
      "--socket-path", "/ipc/node.socket",
      "--topology", "/config/topology.json"
    ]
    volumes:
      - ./config/network/${NETWORK:-preview}:/config
      - node-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"

  ogmios:
    image: cardanosolutions/ogmios:latest-${NETWORK:-preview}
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/config.json"
    ]
    volumes:
      - ./config/network/${NETWORK:-preview}:/config
      - node-ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337

  kupo:
    image: cardanosolutions/kupo
    restart: on-failure
    command: [
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/config.json",
      "--host", "0.0.0.0",
      "--port", "${KUPO_PORT:-1442}",
      "--since", "origin",
      "--prune-utxo",
      "--workdir", "/db",
    ]
    volumes:
      - ./config/network/${NETWORK:-preview}:/config
      - node-ipc:/ipc
      - kupo:/db
    ports:
      - ${KUPO_PORT:-1442}:1442

  nginx:
    build: .
    container_name: nginx
    ports:
      - "1443:80"

volumes:
  node-db:
  node-ipc:
  kupo:
